# .github/workflows/deploy.yml

# Name of the workflow, which will be displayed in the "Actions" tab of your GitHub repository.
name: Deploy Blog to GitHub Pages

# This section defines when the workflow should run.
on:
  push:
    # We only want to run this workflow when changes are pushed to the 'main' branch.
    branches:
      - main

# This section defines the jobs that will be executed as part of the workflow.
jobs:
  # We have a single job named 'deploy'.
  deploy:
    # The type of machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # --- FIX IS HERE ---
    # This block grants the necessary permissions to the GITHUB_TOKEN for this job.
    permissions:
      contents: read      # Allows the job to checkout the repository's code.
      pages: write       # Allows the job to write to the GitHub Pages deployment.
      id-token: write    # Allows the job to get an OIDC token for authentication.

    # This is the sequence of steps that the job will execute.
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the website files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path to the files you want to deploy. '.' means the root of your repository.
          path: '.'

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
